const TENANT_CREATED = 'tenant.TENANT_CREATED';
const TENANT_EMPLOYEE_DATA_IMPORTED = 'tenant.TENANT_EMPLOYEE_DATA_IMPORTED';

const PERSON_CREATED = 'person.PERSON_CREATED';
const PERSON_FIRST_NAME_CHANGED = 'person.PERSON_FIRST_NAME_CHANGED';
const PERSON_LAST_NAME_CHANGED = 'person.PERSON_LAST_NAME_CHANGED';
const PERSON_EMAIL_CHANGED = 'person.PERSON_EMAIL_CHANGED';
const PERSON_PHONE_CHANGED = 'person.PERSON_PHONE_CHANGED';
const PERSON_CARRIER_CHANGED = 'person.PERSON_CARRIER_CHANGED';

const MANAGER_ADDED = 'user.MANAGER_ADDED';
const USER_CREATED = 'user.USER_CREATED';

const PILLAR_CREATED = 'pillar.PILLAR_CREATED';
const PILLAR_DELETED = 'pillar.PILLAR_DELETED';
const PILLAR_NAME_CHANGED = 'pillar.PILLAR_NAME_CHANGED';

const POINT_INCREMENTED = 'point.POINT_INCREMENTED';
const POINT_DECREMENTED = 'point.POINT_DECREMENTED';

const CONTENT_CREATED = 'content.CONTENT_CREATED';
const CONTENT_DELETED = 'content.CONTENT_DELETED';
const CONTENT_TITLE_CHANGED = 'content.CONTENT_TITLE_CHANGED';
const CONTENT_DESCRIPTION_CHANGED = 'content.CONTENT_DESCRIPTION_CHANGED';

module.exports = {
	TENANT_CREATED,
	TENANT_EMPLOYEE_DATA_IMPORTED,
  PERSON_CREATED,
  MANAGER_ADDED,
  USER_CREATED,
	PERSON_FIRST_NAME_CHANGED,
	PERSON_LAST_NAME_CHANGED,
	PERSON_EMAIL_CHANGED,
	PERSON_PHONE_CHANGED,
	PERSON_CARRIER_CHANGED,
	PILLAR_CREATED,
	PILLAR_DELETED,
	PILLAR_NAME_CHANGED,
	POINT_INCREMENTED,
	POINT_DECREMENTED,
	CONTENT_CREATED,
	CONTENT_DELETED,
	CONTENT_TITLE_CHANGED,
	CONTENT_DESCRIPTION_CHANGED
};
