const TENANT_CREATED = 'tenant.TENANT_CREATED';
const TENANT_EMPLOYEE_DATA_IMPORTED = 'tenant.TENANT_EMPLOYEE_DATA_IMPORTED';
const PERSON_CREATED = 'person.PERSON_CREATED';
const MANAGER_ADDED = 'user.MANAGER_ADDED';
const USER_CREATED = 'user.USER_CREATED';
const PILLAR_CREATED = 'pillar.PILLAR_CREATED';
const PILLAR_DELETED = 'pillar.PILLAR_DELETED';
const PILLAR_NAME_CHANGED = 'pillar.PILLAR_NAME_CHANGED';

module.exports = {
	TENANT_CREATED,
	TENANT_EMPLOYEE_DATA_IMPORTED,
        PERSON_CREATED,
        MANAGER_ADDED,
        USER_CREATED,
	PERSON_CREATED,
	PILLAR_CREATED,
	PILLAR_DELETED,
	PILLAR_NAME_CHANGED
};
