const PILLAR_CREATE = 'command.PILLAR_CREATE';
const PILLAR_DELETE = 'command.PILLAR_DELETE';
const PILLAR_NAME_CHANGE = 'command.PILLAR_NAME_CHANGE';

module.exports = {
	PILLAR_CREATE,
	PILLAR_DELETE,
	PILLAR_NAME_CHANGE
};
