const PILLAR_CREATED = 'pillar.PILLAR_CREATED';
const PILLAR_DELETED = 'pillar.PILLAR_DELETED';
const PILLAR_NAME_CHANGED = 'pillar.PILLAR_NAME_CHANGED';

module.exports = {
	PILLAR_CREATED,
	PILLAR_DELETED,
	PILLAR_NAME_CHANGED
};
