const CONTENT_CREATE = 'command.CONTENT_CREATE';
const CONTENT_DELETE = 'command.CONTENT_DELETE';
const CONTENT_TITLE_CHANGE = 'command.CONTENT_TITLE_CHANGE';
const CONTENT_DESCRIPTION_CHANGE = 'command.CONTENT_DESCRIPTION_CHANGE';

module.exports = {
	CONTENT_CREATE,
	CONTENT_DELETE,
	CONTENT_TITLE_CHANGE,
	CONTENT_DESCRIPTION_CHANGE
};
