const CONTENT_CREATE = 'command.CONTENT_CREATE';
const CONTENT_DELETE = 'command.CONTENT_DELETE';
const CONTENT_TITLE_CHANGE = 'command.CONTENT_TITLE_CHANGE';
const CONTENT_URL_CHANGE = 'command.CONTENT_URL_CHANGE';
const CONTENT_QUOTE_CHANGE = 'command.CONTENT_QUOTE_CHANGE';
const CONTENT_DESCRIPTION_CHANGE = 'command.CONTENT_DESCRIPTION_CHANGE';
const CONTENT_AUTHOR_CHANGE = 'command.CONTENT_AUTHOR_CHANGE';
const CONTENT_RECIPIENT_CHANGE = 'command.CONTENT_RECIPIENT_CHANGE';
const CONTENT_RECIPIENT_POSITION_CHANGE = 'command.CONTENT_RECIPIENT_POSITION_CHANGE';

module.exports = {
	CONTENT_CREATE,
	CONTENT_DELETE,
	CONTENT_TITLE_CHANGE,
	CONTENT_URL_CHANGE,
	CONTENT_QUOTE_CHANGE,
	CONTENT_AUTHOR_CHANGE,
	CONTENT_RECIPIENT_CHANGE,
	CONTENT_RECIPIENT_POSITION_CHANGE,
	CONTENT_DESCRIPTION_CHANGE
};
