const CONTENT_CREATED = 'content.CONTENT_CREATED';
const CONTENT_DELETED = 'content.CONTENT_DELETED';
const CONTENT_TITLE_CHANGED = 'content.CONTENT_TITLE_CHANGED';
const CONTENT_DESCRIPTION_CHANGED = 'content.CONTENT_DESCRIPTION_CHANGED';

module.exports = {
	CONTENT_CREATED,
	CONTENT_DELETED,
	CONTENT_TITLE_CHANGED,
	CONTENT_DESCRIPTION_CHANGED
};
