const CONTENT_CREATED = 'content.CONTENT_CREATED';
const CONTENT_DELETED = 'content.CONTENT_DELETED';
const CONTENT_TITLE_CHANGED = 'content.CONTENT_TITLE_CHANGED';
const CONTENT_URL_CHANGED = 'content.CONTENT_URL_CHANGED';
const CONTENT_QUOTE_CHANGED = 'content.CONTENT_QUOTE_CHANGED';
const CONTENT_DESCRIPTION_CHANGED = 'content.CONTENT_DESCRIPTION_CHANGED';
const CONTENT_AUTHOR_CHANGED = 'content.CONTENT_AUTHOR_CHANGED';
const CONTENT_RECIPIENT_CHANGED = 'content.CONTENT_RECIPIENT_CHANGED';
const CONTENT_RECIPIENT_POSITION_CHANGED = 'content.CONTENT_RECIPIENT_POSITION_CHANGED';
const CONTENT_RICHTEXT_CHANGED = 'content.CONTENT_RICHTEXT_CHANGED';

module.exports = {
	CONTENT_CREATED,
	CONTENT_DELETED,
	CONTENT_TITLE_CHANGED,
	CONTENT_URL_CHANGED,
	CONTENT_QUOTE_CHANGED,
	CONTENT_AUTHOR_CHANGED,
	CONTENT_RECIPIENT_CHANGED,
	CONTENT_RECIPIENT_POSITION_CHANGED,
	CONTENT_DESCRIPTION_CHANGED,
	CONTENT_RICHTEXT_CHANGED,
};
