const PERSON_CREATE = 'command.PERSON_CREATE';
const PERSON_FIRST_NAME_CHANGE = 'command.PERSON_FIRST_NAME_CHANGE';
const PERSON_LAST_NAME_CHANGE = 'command.PERSON_LAST_NAME_CHANGE';
const PERSON_EMAIL_CHANGE = 'command.PERSON_EMAIL_CHANGE';
const PERSON_PHONE_CHANGE = 'command.PERSON_PHONE_CHANGE';
const PERSON_CARRIER_CHANGE = 'command.PERSON_CARRIER_CHANGE';

module.exports = {
	PERSON_CREATE,
	PERSON_FIRST_NAME_CHANGE,
	PERSON_LAST_NAME_CHANGE,
	PERSON_EMAIL_CHANGE,
	PERSON_PHONE_CHANGE,
	PERSON_CARRIER_CHANGE
};
