const USER_CREATED = 'user.USER_CREATED';
const POINT_INCREMENTED = 'point.POINT_INCREMENTED';
const POINT_DECREMENTED = 'point.POINT_DECREMENTED';

module.exports = {
	USER_CREATED,
	POINT_INCREMENTED,
	POINT_DECREMENTED
};
