const VALIDATION_ERROR = 'VALIDATION_ERROR';
const SERVER_ERROR = 'SERVER_ERROR';
const INVALID_ERROR = 'INVALID_ERROR';
const BAD_REQUEST = 'BAD_REQUEST';

module.exports = {
	VALIDATION_ERROR,
	SERVER_ERROR,
	INVALID_ERROR,
	BAD_REQUEST
};
