const TENANT_CREATED = 'tenant.TENANT_CREATED';
const TENANT_EMPLOYEE_DATA_IMPORTED = 'tenant.TENANT_EMPLOYEE_DATA_IMPORTED';

const PRODUCT_COMPLETED = 'product.PRODUCT_COMPLETED';
const PRODUCT_IMPROVED = 'product.PRODUCT_IMPROVED';
const PRODUCT_STARTED = 'product.PRODUCT_STARTED';
const PROPOSAL_CREATED = 'proposal.PROPOSAL_CREATED';

module.exports = {
	TENANT_CREATED,
	TENANT_EMPLOYEE_DATA_IMPORTED,
	PRODUCT_COMPLETED,
	PRODUCT_IMPROVED,
	PRODUCT_STARTED,
	PROPOSAL_CREATED
};