const PRODUCT_COMPLETE = 'command.PRODUCT_COMPLETE';
const PRODUCT_IMPROVE = 'command.PRODUCT_IMPROVE';
const PRODUCT_START = 'command.PRODUCT_START';

module.exports = {
	PRODUCT_COMPLETE,
	PRODUCT_IMPROVE,
	PRODUCT_START
};