const PRODUCT_COMPLETED = 'product.PRODUCT_COMPLETED';
const PRODUCT_IMPROVED = 'product.PRODUCT_IMPROVED';
const PRODUCT_STARTED = 'product.PRODUCT_STARTED';

const PROPOSAL_CREATED = 'proposal.PROPOSAL_CREATED';

module.exports = {
	PRODUCT_COMPLETED,
	PRODUCT_IMPROVED,
	PRODUCT_STARTED,
	PROPOSAL_CREATED
};